// Generated by gencpp from file swj_socket/heartsendflag.msg
// DO NOT EDIT!


#ifndef SWJ_SOCKET_MESSAGE_HEARTSENDFLAG_H
#define SWJ_SOCKET_MESSAGE_HEARTSENDFLAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swj_socket
{
template <class ContainerAllocator>
struct heartsendflag_
{
  typedef heartsendflag_<ContainerAllocator> Type;

  heartsendflag_()
    : heartsendflag(0)  {
    }
  heartsendflag_(const ContainerAllocator& _alloc)
    : heartsendflag(0)  {
  (void)_alloc;
    }



   typedef int8_t _heartsendflag_type;
  _heartsendflag_type heartsendflag;




  typedef boost::shared_ptr< ::swj_socket::heartsendflag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swj_socket::heartsendflag_<ContainerAllocator> const> ConstPtr;

}; // struct heartsendflag_

typedef ::swj_socket::heartsendflag_<std::allocator<void> > heartsendflag;

typedef boost::shared_ptr< ::swj_socket::heartsendflag > heartsendflagPtr;
typedef boost::shared_ptr< ::swj_socket::heartsendflag const> heartsendflagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swj_socket::heartsendflag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swj_socket::heartsendflag_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace swj_socket

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'swj_socket': ['/home/lgl/master/mechanical_arm/arm/src/swj_socket/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::swj_socket::heartsendflag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swj_socket::heartsendflag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swj_socket::heartsendflag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swj_socket::heartsendflag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swj_socket::heartsendflag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swj_socket::heartsendflag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swj_socket::heartsendflag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77c4bcaf053909a4f759348601592667";
  }

  static const char* value(const ::swj_socket::heartsendflag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77c4bcaf053909a4ULL;
  static const uint64_t static_value2 = 0xf759348601592667ULL;
};

template<class ContainerAllocator>
struct DataType< ::swj_socket::heartsendflag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swj_socket/heartsendflag";
  }

  static const char* value(const ::swj_socket::heartsendflag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swj_socket::heartsendflag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 heartsendflag\n\
";
  }

  static const char* value(const ::swj_socket::heartsendflag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swj_socket::heartsendflag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heartsendflag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct heartsendflag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swj_socket::heartsendflag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swj_socket::heartsendflag_<ContainerAllocator>& v)
  {
    s << indent << "heartsendflag: ";
    Printer<int8_t>::stream(s, indent + "  ", v.heartsendflag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWJ_SOCKET_MESSAGE_HEARTSENDFLAG_H
