// Generated by gencpp from file swj_socket/statefeed.msg
// DO NOT EDIT!


#ifndef SWJ_SOCKET_MESSAGE_STATEFEED_H
#define SWJ_SOCKET_MESSAGE_STATEFEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swj_socket
{
template <class ContainerAllocator>
struct statefeed_
{
  typedef statefeed_<ContainerAllocator> Type;

  statefeed_()
    : check_node(0)
    , Pressure(0.0)
    , mobot_mode()
    , vehicle_mode()  {
    }
  statefeed_(const ContainerAllocator& _alloc)
    : check_node(0)
    , Pressure(0.0)
    , mobot_mode(_alloc)
    , vehicle_mode(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _check_node_type;
  _check_node_type check_node;

   typedef float _Pressure_type;
  _Pressure_type Pressure;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mobot_mode_type;
  _mobot_mode_type mobot_mode;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _vehicle_mode_type;
  _vehicle_mode_type vehicle_mode;




  typedef boost::shared_ptr< ::swj_socket::statefeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swj_socket::statefeed_<ContainerAllocator> const> ConstPtr;

}; // struct statefeed_

typedef ::swj_socket::statefeed_<std::allocator<void> > statefeed;

typedef boost::shared_ptr< ::swj_socket::statefeed > statefeedPtr;
typedef boost::shared_ptr< ::swj_socket::statefeed const> statefeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swj_socket::statefeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swj_socket::statefeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace swj_socket

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'swj_socket': ['/home/lgl/master/mechanical_arm/arm/src/swj_socket/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::swj_socket::statefeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swj_socket::statefeed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swj_socket::statefeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swj_socket::statefeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swj_socket::statefeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swj_socket::statefeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swj_socket::statefeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e249da119c5a3c0bedbd44f53561933";
  }

  static const char* value(const ::swj_socket::statefeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e249da119c5a3c0ULL;
  static const uint64_t static_value2 = 0xbedbd44f53561933ULL;
};

template<class ContainerAllocator>
struct DataType< ::swj_socket::statefeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swj_socket/statefeed";
  }

  static const char* value(const ::swj_socket::statefeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swj_socket::statefeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 check_node\n\
float32 Pressure\n\
string mobot_mode\n\
string vehicle_mode\n\
";
  }

  static const char* value(const ::swj_socket::statefeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swj_socket::statefeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.check_node);
      stream.next(m.Pressure);
      stream.next(m.mobot_mode);
      stream.next(m.vehicle_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct statefeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swj_socket::statefeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swj_socket::statefeed_<ContainerAllocator>& v)
  {
    s << indent << "check_node: ";
    Printer<int32_t>::stream(s, indent + "  ", v.check_node);
    s << indent << "Pressure: ";
    Printer<float>::stream(s, indent + "  ", v.Pressure);
    s << indent << "mobot_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mobot_mode);
    s << indent << "vehicle_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.vehicle_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWJ_SOCKET_MESSAGE_STATEFEED_H
